/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Example */

#ifndef _Included_Example
#define _Included_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Example
 * Method:    callNative
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_Example_callNative
  (JNIEnv *, jobject, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
