/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SysInfo */

#ifndef _Included_SysInfo
#define _Included_SysInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SysInfo
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SysInfo_getString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SysInfo
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SysInfo_getInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     SysInfo
 * Method:    getFloat
 * Signature: (Ljava/lang/Float;)Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_SysInfo_getFloat
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
